# Тема 1 "Вычисление с помощью Numpy"

### Задание 1 

In [2]:
import numpy as np
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])
mean_a = np.mean(a, axis = 0)

In [4]:
mean_a

array([2. , 8.4])

### Задание 2

In [5]:
a_centered = np.subtract(a, mean_a)

In [6]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [21]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [22]:
a_centered_sp

8.0

In [23]:
a_covariance = a_centered_sp / (a.shape[0] - 1)

In [24]:
a_covariance

2.0

##### Доп. задание по функции dot

In [52]:
a = np.array([2, 1, 7, 8])
b = np.array([5, 1, 6, 9])
np.dot(a, b) #умножение двух одномерных массивов

125

In [55]:
a = np.array([[2, 1, 7],
             [10, 12, 14]])
b = np.array([[5, 1],
             [4, 10],
             [13, 15]])
np.dot(a, b) #умножение матриц(обязательно должно совпадать кол-во столбцов в перовй матрице и кол-во строк во второй)

array([[105, 117],
       [280, 340]])

In [57]:
a = np.arange(3*2*4).reshape(3, 2, 4)
np.dot(a, -21239)# обычное произведение на число, супер маленькое:)

array([[[      0,  -21239,  -42478,  -63717],
        [ -84956, -106195, -127434, -148673]],

       [[-169912, -191151, -212390, -233629],
        [-254868, -276107, -297346, -318585]],

       [[-339824, -361063, -382302, -403541],
        [-424780, -446019, -467258, -488497]]])

### Задание 4**


In [25]:
np.cov(m = a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

# Работа с данными в Pandas

### Задание 1

In [26]:
import pandas as pd
authors = pd.DataFrame({'author_id':[1, 2, 3],
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, columns= ['author_id', 'author_name'])
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                        'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                        'price':[450, 300, 350, 500, 450, 370, 290]}, columns= ['author_id', 'book_title', 'price'])

### Задание 2


In [27]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')

In [28]:
authors_price


author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


### Задание 3

In [29]:
top_5 = pd.DataFrame(authors_price.nlargest(5, 'price'))


In [30]:
top_5


author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4


In [31]:
authors_stat = authors_price.groupby('author_name').agg({'price':['max', 'min', 'mean']})


In [32]:
authors_stat

price                 
              max  min        mean
author_name                       
Островский    370  290  330.000000
Тургенев      450  300  366.666667
Чехов         500  450  475.000000

### Задание 5

In [33]:
for index, row in authors_price.iterrows(): authors_price.at[index, 'cover'] = 'new value' 

In [34]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [35]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [44]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover', aggfunc='sum', fill_value=0)

In [45]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [46]:
book_info.to_pickle('book_info.pkl')


In [48]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950